default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/joshuachp/pre-commit-hooks
    rev: 0.1.41
    hooks:
      - id: committed
      - id: typos
      - id: rust-fmt
      - id: rust-build
      - id: rust-clippy
      - id: rust-doc
      - id: rust-nextest
      - id: rust-test-doc
      - id: rust-hack
      - id: rust-min-ver
  - repo: local
    hooks:
      - id: rust-msrv
        name: check rust msrv
        description: Check the MSRV
        language: system
        pass_filenames: false
        entry: cargo +1.72.1 check --all-features
